#!/bin/bash
#This script file merges files from the /dist folder into the /site-template folder, to generate
#a complete ConnextCMS site template.

echo "building connextcms-vue-app directory..."

rm -rf connextcms-vue-app
cp -r site-template-connextcms connextcms-vue-app
cd dist
cp index.html ../connextcms-vue-app/keystone/templates/views/appdashboard.hbs
cd static
mkdir ../../connextcms-vue-app/public
mkdir ../../connextcms-vue-app/public/static
cp -r css ../../connextcms-vue-app/public/static/css
cp -r img ../../connextcms-vue-app/public/static/img
cp -r js ../../connextcms-vue-app/public/static/js

echo "...Done!"