#!/bin/bash
# This script copied the files from the coPilot repo to the test installation
# of ConnextCMS on my dev server. It allows me to do rapid testing of code
# chanages.

cp -r connextcms-vue-app ~/test-connextcms/theme/
